version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
